---
- name: Bootstrap zer0 instance with Docker & dependencies
  hosts: ansible_client
  remote_user: ubuntu
  become: true
  vars:
    docker_compose_version: "1.29.2"
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - containerd
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install pip for Docker Compose
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
